apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
    labels: 
        app: worker-deployment
spec:
    replicas: 4
    selector: 
        matchLabels:
            app: workerapp
    template:
        metadata:
            labels:
                app: workerapp
        spec:
            containers:
                - name: workerapp
                  image: consumer-worker:latest
                  ports:
                    - containerPort: 8080
                  imagePullPolicy: Never
                  env:
                  - name: ConnectionStrings__Database
                    value: "Host=host.docker.internal;Port=5433;Database=mydb;Username=postgres;Password=postgres"
                  - name: RabbitMQ__Host
                    value: "host.docker.internal"
                  - name: RabbitMQ__Username
                    value: "user"
                  - name: RabbitMQ__Password
                    value: "password"
                  - name: Seq__Url
                    value: "http://host.docker.internal:5341/"