apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config-map
data:
  rabbitmq_host: "rabbitmq-service"
  seq_host: "http://seq-service:5341/"
  postgres_host: "postgres"
  connection_string: "Host=postgres;Port=5433;Database=mydb;Username=postgres;Password=postgres"