apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumerapp
  template:
    metadata:
      labels:
        app: consumerapp
    spec:
      containers:
        - name: consumerapp
          image: consumer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
          - name: RabbitMQ__Host
            valueFrom: 
              configMapKeyRef:
                name: consumer-config-map
                key: rabbitmq_host
          - name: Seq__Url
            valueFrom:
              configMapKeyRef:
                name: consumer-config-map
                key: seq_host
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: consumer-secret
                key: RabbitMQ__Username
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: consumer-secret
                key: RabbitMQ__Password
          - name: ConnectionStrings__Database
            valueFrom:
              secretKeyRef:
                name: consumer-secret
                key: ConnectionStrings__Database