apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
  name: consumer-scale
spec:
  scaleTargetRef: 
    name: consumer-deployment
  minReplicaCount: 0
  maxReplicaCount: 10 
  triggers:
  - type: rabbitmq
    metadata:
      queueName: "sensor-data"
      queueLength: "10"
      host: amqp://user:password@rabbitmq-service.default.svc.cluster.local:5672

