apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
type: Opaque
data:
  RabbitMQ__Username: dXNlcg==
  RabbitMQ__Password: cGFzc3dvcmQ=
  RabbitMQ__HostString: YW1xcDovL3VzZXI6cGFzc3dvcmRAcmFiYml0bXEtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=