apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
type: Opaque
data:
  RabbitMQ__Username: dXNlcg==
  RabbitMQ__Password: cGFzc3dvcmQ=
  RabbitMQ__HostString: YW1xcDovL3VzZXI6cGFzc3dvcmRAcmFiYml0bXEtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  ConnectionStrings__Database: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9bXlkYjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlcw==