// <auto-generated />
using System;
using Consumer.Worker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consumer.Worker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consumer.Worker.Data.AccidentByState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgSeverity")
                        .HasColumnType("double precision");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("AccidentsByState");
                });

            modelBuilder.Entity("Consumer.Worker.Data.AccidentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Amenity")
                        .HasColumnType("boolean");

                    b.Property<string>("AstronomicalTwilight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Bump")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CivilTwilight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Crossing")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DistanceMi")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndLng")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GiveWay")
                        .HasColumnType("boolean");

                    b.Property<double?>("HumidityPct")
                        .HasColumnType("double precision");

                    b.Property<bool>("Junction")
                        .HasColumnType("boolean");

                    b.Property<string>("NauticalTwilight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NoExit")
                        .HasColumnType("boolean");

                    b.Property<double?>("PrecipitationIn")
                        .HasColumnType("double precision");

                    b.Property<double?>("PressureIn")
                        .HasColumnType("double precision");

                    b.Property<bool>("Railway")
                        .HasColumnType("boolean");

                    b.Property<bool>("Roundabout")
                        .HasColumnType("boolean");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("StartLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartLng")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Station")
                        .HasColumnType("boolean");

                    b.Property<bool>("Stop")
                        .HasColumnType("boolean");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SunriseSunset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("TemperatureF")
                        .HasColumnType("double precision");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrafficCalming")
                        .HasColumnType("boolean");

                    b.Property<bool>("TrafficSignal")
                        .HasColumnType("boolean");

                    b.Property<bool>("TurningLoop")
                        .HasColumnType("boolean");

                    b.Property<double?>("VisibilityMi")
                        .HasColumnType("double precision");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("WeatherTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WindChillF")
                        .HasColumnType("double precision");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("WindSpeedMph")
                        .HasColumnType("double precision");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccidentRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
