apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: worker-scaler

spec:
    scaleTargetRef:
        name: worker-deployment
    minReplicaCount: 4
    maxReplicaCount: 10
    triggers:
    - type: rabbitmq
      metadata:
        queueName: nov
        queueLength: "5"
        host: amqp://user:password@host.docker.internal:5672