apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config-map
data:
  rabbitmq_host: "host.minikube.internal"
  seq_host: "http://host.minikube.internal:5341/"
  file_path: "/app/data/US_Accidents_March23.csv"