apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producerapp
  template:
    metadata:
      labels:
        app: producerapp
    spec:
      containers:
        - name: producerapp
          image: producer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DOTNET_USE_POLLING_FILE_WATCHER
              value: "true"
            - name: Seq__ServerUrl
              valueFrom:
                configMapKeyRef:
                  name: producer-config-map
                  key: seq_host
            - name: AppSettings__FilePath
              valueFrom:
                configMapKeyRef:
                  name: producer-config-map
                  key: file_path
            - name: RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: RabbitMQ__Host
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: RabbitMQ__Username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: RabbitMQ__Password
          volumeMounts:
            - name: stream-config
              mountPath: /config
          resources: 
            requests: 
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: stream-config
          configMap:
            name: stream-config