services:
  message-broker:
    image: rabbitmq:3-management
    container_name: message-broker
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    network:
      - sir_net
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    newtorks:
      - sir_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - sir_net
  
  seq: 
    image: datalust/seq:latest
    container_name: seq
    ports: 
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: "MyStrongPassword123!"
    volumes:
      - seq_data:/data
    networks:
      - sir_net

volumes:
  rabbitmq_data:
  pgdata:
  pgadmin_data:
  seq_data:
networks:
  sir_net